### ISSUE TITLE
can't start server

### ISSUE THREAD

**Issue by Gragenio** [mmmaxwwwell/space-engineers-dedicated-docker-linux#70]
Hi, i tried following all the steps but i'm not able to start the server.
this is my log:

space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:31.440: Environment.Is64BitProcess: True
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:31.440: Environment.Is64BitOperatingSystem: True
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:31.440: Environment.Version: .NET Framework 4.8.3761.0
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:31.440: Environment.CurrentDirectory: Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:31.440: CPU Info: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
space-engineers-dedicated-docker-linux  | Computer does not meet minimum requirements, forcing Experimental mode
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:37.933: Bind IP : 0.0.0.0:27016
space-engineers-dedicated-docker-linux  | <?xml version="1.0"?>
space-engineers-dedicated-docker-linux  | <MyConfigDedicated xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
space-engineers-dedicated-docker-linux  |   <SessionSettings>
space-engineers-dedicated-docker-linux  |     <GameMode>Survival</GameMode>
space-engineers-dedicated-docker-linux  |     <InventorySizeMultiplier>3</InventorySizeMultiplier>
space-engineers-dedicated-docker-linux  |     <BlocksInventorySizeMultiplier>1</BlocksInventorySizeMultiplier>
space-engineers-dedicated-docker-linux  |     <AssemblerSpeedMultiplier>3</AssemblerSpeedMultiplier>
space-engineers-dedicated-docker-linux  |     <AssemblerEfficiencyMultiplier>3</AssemblerEfficiencyMultiplier>
space-engineers-dedicated-docker-linux  |     <RefinerySpeedMultiplier>3</RefinerySpeedMultiplier>
space-engineers-dedicated-docker-linux  |     <OnlineMode>PUBLIC</OnlineMode>
space-engineers-dedicated-docker-linux  |     <MaxPlayers>16</MaxPlayers>
space-engineers-dedicated-docker-linux  |     <MaxFloatingObjects>100</MaxFloatingObjects>
space-engineers-dedicated-docker-linux  |     <MaxBackupSaves>5</MaxBackupSaves>
space-engineers-dedicated-docker-linux  |     <MaxGridSize>0</MaxGridSize>
space-engineers-dedicated-docker-linux  |     <MaxBlocksPerPlayer>0</MaxBlocksPerPlayer>
space-engineers-dedicated-docker-linux  |     <TotalPCU>320000</TotalPCU>
space-engineers-dedicated-docker-linux  |     <PiratePCU>50000</PiratePCU>
space-engineers-dedicated-docker-linux  |     <MaxFactionsCount>0</MaxFactionsCount>
space-engineers-dedicated-docker-linux  |     <BlockLimitsEnabled>PER_PLAYER</BlockLimitsEnabled>
space-engineers-dedicated-docker-linux  |     <EnableRemoteBlockRemoval>true</EnableRemoteBlockRemoval>
space-engineers-dedicated-docker-linux  |     <EnvironmentHostility>SAFE</EnvironmentHostility>
space-engineers-dedicated-docker-linux  |     <AutoHealing>true</AutoHealing>
space-engineers-dedicated-docker-linux  |     <EnableCopyPaste>false</EnableCopyPaste>
space-engineers-dedicated-docker-linux  |     <WeaponsEnabled>true</WeaponsEnabled>
space-engineers-dedicated-docker-linux  |     <ShowPlayerNamesOnHud>true</ShowPlayerNamesOnHud>
space-engineers-dedicated-docker-linux  |     <ThrusterDamage>true</ThrusterDamage>
space-engineers-dedicated-docker-linux  |     <CargoShipsEnabled>true</CargoShipsEnabled>
space-engineers-dedicated-docker-linux  |     <EnableSpectator>false</EnableSpectator>
space-engineers-dedicated-docker-linux  |     <WorldSizeKm>0</WorldSizeKm>
space-engineers-dedicated-docker-linux  |     <RespawnShipDelete>true</RespawnShipDelete>
space-engineers-dedicated-docker-linux  |     <ResetOwnership>false</ResetOwnership>
space-engineers-dedicated-docker-linux  |     <WelderSpeedMultiplier>2</WelderSpeedMultiplier>
space-engineers-dedicated-docker-linux  |     <GrinderSpeedMultiplier>2</GrinderSpeedMultiplier>
space-engineers-dedicated-docker-linux  |     <RealisticSound>false</RealisticSound>
space-engineers-dedicated-docker-linux  |     <HackSpeedMultiplier>0.33</HackSpeedMultiplier>
space-engineers-dedicated-docker-linux  |     <PermanentDeath>false</PermanentDeath>
space-engineers-dedicated-docker-linux  |     <AutoSaveInMinutes>5</AutoSaveInMinutes>
space-engineers-dedicated-docker-linux  |     <EnableSaving>true</EnableSaving>
space-engineers-dedicated-docker-linux  |     <InfiniteAmmo>false</InfiniteAmmo>
space-engineers-dedicated-docker-linux  |     <EnableContainerDrops>false</EnableContainerDrops>
space-engineers-dedicated-docker-linux  |     <SpawnShipTimeMultiplier>0</SpawnShipTimeMultiplier>
space-engineers-dedicated-docker-linux  |     <ProceduralDensity>0.35</ProceduralDensity>
space-engineers-dedicated-docker-linux  |     <ProceduralSeed>0</ProceduralSeed>
space-engineers-dedicated-docker-linux  |     <DestructibleBlocks>true</DestructibleBlocks>
space-engineers-dedicated-docker-linux  |     <EnableIngameScripts>true</EnableIngameScripts>
space-engineers-dedicated-docker-linux  |     <ViewDistance>15000</ViewDistance>
space-engineers-dedicated-docker-linux  |     <EnableToolShake>true</EnableToolShake>
space-engineers-dedicated-docker-linux  |     <VoxelGeneratorVersion>4</VoxelGeneratorVersion>
space-engineers-dedicated-docker-linux  |     <EnableOxygen>true</EnableOxygen>
space-engineers-dedicated-docker-linux  |     <EnableOxygenPressurization>true</EnableOxygenPressurization>
space-engineers-dedicated-docker-linux  |     <Enable3rdPersonView>true</Enable3rdPersonView>
space-engineers-dedicated-docker-linux  |     <EnableEncounters>true</EnableEncounters>
space-engineers-dedicated-docker-linux  |     <EnableConvertToStation>true</EnableConvertToStation>
space-engineers-dedicated-docker-linux  |     <StationVoxelSupport>false</StationVoxelSupport>
space-engineers-dedicated-docker-linux  |     <EnableSunRotation>true</EnableSunRotation>
space-engineers-dedicated-docker-linux  |     <EnableRespawnShips>true</EnableRespawnShips>
space-engineers-dedicated-docker-linux  |     <ScenarioEditMode>false</ScenarioEditMode>
space-engineers-dedicated-docker-linux  |     <Scenario>false</Scenario>
space-engineers-dedicated-docker-linux  |     <CanJoinRunning>false</CanJoinRunning>
space-engineers-dedicated-docker-linux  |     <PhysicsIterations>8</PhysicsIterations>
space-engineers-dedicated-docker-linux  |     <SunRotationIntervalMinutes>119.999992</SunRotationIntervalMinutes>
space-engineers-dedicated-docker-linux  |     <EnableJetpack>true</EnableJetpack>
space-engineers-dedicated-docker-linux  |     <SpawnWithTools>true</SpawnWithTools>
space-engineers-dedicated-docker-linux  |     <StartInRespawnScreen>false</StartInRespawnScreen>
space-engineers-dedicated-docker-linux  |     <EnableVoxelDestruction>true</EnableVoxelDestruction>
space-engineers-dedicated-docker-linux  |     <MaxDrones>5</MaxDrones>
space-engineers-dedicated-docker-linux  |     <EnableDrones>true</EnableDrones>
space-engineers-dedicated-docker-linux  |     <EnableWolfs>false</EnableWolfs>
space-engineers-dedicated-docker-linux  |     <EnableSpiders>false</EnableSpiders>
space-engineers-dedicated-docker-linux  |     <FloraDensityMultiplier>1</FloraDensityMultiplier>
space-engineers-dedicated-docker-linux  |     <EnableStructuralSimulation>false</EnableStructuralSimulation>
space-engineers-dedicated-docker-linux  |     <MaxActiveFracturePieces>50</MaxActiveFracturePieces>
space-engineers-dedicated-docker-linux  |     <BlockTypeLimits>
space-engineers-dedicated-docker-linux  |       <dictionary>
space-engineers-dedicated-docker-linux  |       </dictionary>
space-engineers-dedicated-docker-linux  |     </BlockTypeLimits>
space-engineers-dedicated-docker-linux  |     <EnableScripterRole>true</EnableScripterRole>
space-engineers-dedicated-docker-linux  |     <MinDropContainerRespawnTime>5</MinDropContainerRespawnTime>
space-engineers-dedicated-docker-linux  |     <MaxDropContainerRespawnTime>8</MaxDropContainerRespawnTime>
space-engineers-dedicated-docker-linux  |     <EnableTurretsFriendlyFire>false</EnableTurretsFriendlyFire>
space-engineers-dedicated-docker-linux  |     <EnableSubgridDamage>false</EnableSubgridDamage>
space-engineers-dedicated-docker-linux  |     <SyncDistance>3000</SyncDistance>
space-engineers-dedicated-docker-linux  |     <ExperimentalMode>true</ExperimentalMode>
space-engineers-dedicated-docker-linux  |     <AdaptiveSimulationQuality>true</AdaptiveSimulationQuality>
space-engineers-dedicated-docker-linux  |     <EnableVoxelHand>true</EnableVoxelHand>
space-engineers-dedicated-docker-linux  |     <RemoveOldIdentitiesH>0</RemoveOldIdentitiesH>
space-engineers-dedicated-docker-linux  |     <TrashRemovalEnabled>true</TrashRemovalEnabled>
space-engineers-dedicated-docker-linux  |     <StopGridsPeriodMin>15</StopGridsPeriodMin>
space-engineers-dedicated-docker-linux  |     <TrashFlagsValue>7706</TrashFlagsValue>
space-engineers-dedicated-docker-linux  |     <AFKTimeountMin>0</AFKTimeountMin>
space-engineers-dedicated-docker-linux  |     <BlockCountThreshold>20</BlockCountThreshold>
space-engineers-dedicated-docker-linux  |     <PlayerDistanceThreshold>500</PlayerDistanceThreshold>
space-engineers-dedicated-docker-linux  |     <OptimalGridCount>0</OptimalGridCount>
space-engineers-dedicated-docker-linux  |     <PlayerInactivityThreshold>0</PlayerInactivityThreshold>
space-engineers-dedicated-docker-linux  |     <PlayerCharacterRemovalThreshold>15</PlayerCharacterRemovalThreshold>
space-engineers-dedicated-docker-linux  |     <VoxelTrashRemovalEnabled>false</VoxelTrashRemovalEnabled>
space-engineers-dedicated-docker-linux  |     <VoxelPlayerDistanceThreshold>5000</VoxelPlayerDistanceThreshold>
space-engineers-dedicated-docker-linux  |     <VoxelGridDistanceThreshold>5000</VoxelGridDistanceThreshold>
space-engineers-dedicated-docker-linux  |     <VoxelAgeThreshold>24</VoxelAgeThreshold>
space-engineers-dedicated-docker-linux  |     <EnableResearch>true</EnableResearch>
space-engineers-dedicated-docker-linux  |     <EnableGoodBotHints>true</EnableGoodBotHints>
space-engineers-dedicated-docker-linux  |     <OptimalSpawnDistance>50000</OptimalSpawnDistance>
space-engineers-dedicated-docker-linux  |     <EnableAutorespawn>true</EnableAutorespawn>
space-engineers-dedicated-docker-linux  |     <EnableBountyContracts>true</EnableBountyContracts>
space-engineers-dedicated-docker-linux  |     <EnableSupergridding>false</EnableSupergridding>
space-engineers-dedicated-docker-linux  |     <EnableEconomy>true</EnableEconomy>
space-engineers-dedicated-docker-linux  |     <DepositsCountCoefficient>1</DepositsCountCoefficient>
space-engineers-dedicated-docker-linux  |     <DepositSizeDenominator>60</DepositSizeDenominator>
space-engineers-dedicated-docker-linux  |     <WeatherSystem>true</WeatherSystem>
space-engineers-dedicated-docker-linux  |     <HarvestRatioMultiplier>0.8</HarvestRatioMultiplier>
space-engineers-dedicated-docker-linux  |     <TradeFactionsCount>15</TradeFactionsCount>
space-engineers-dedicated-docker-linux  |     <StationsDistanceInnerRadius>10000000</StationsDistanceInnerRadius>
space-engineers-dedicated-docker-linux  |     <StationsDistanceOuterRadiusStart>10000000</StationsDistanceOuterRadiusStart>
space-engineers-dedicated-docker-linux  |     <StationsDistanceOuterRadiusEnd>30000000</StationsDistanceOuterRadiusEnd>
space-engineers-dedicated-docker-linux  |     <EconomyTickInSeconds>1200</EconomyTickInSeconds>
space-engineers-dedicated-docker-linux  |     <SimplifiedSimulation>false</SimplifiedSimulation>
space-engineers-dedicated-docker-linux  |     <SuppressedWarnings />
space-engineers-dedicated-docker-linux  |     <EnablePcuTrading>true</EnablePcuTrading>
space-engineers-dedicated-docker-linux  |     <FamilySharing>true</FamilySharing>
space-engineers-dedicated-docker-linux  |     <EnableSelectivePhysicsUpdates>false</EnableSelectivePhysicsUpdates>
space-engineers-dedicated-docker-linux  |   </SessionSettings>
space-engineers-dedicated-docker-linux  | <LoadWorld>Z:\appdata\space-engineers\World\World</LoadWorld>
space-engineers-dedicated-docker-linux  |   <IP>0.0.0.0</IP>
space-engineers-dedicated-docker-linux  |   <SteamPort>8766</SteamPort>
space-engineers-dedicated-docker-linux  |   <ServerPort>27016</ServerPort>
space-engineers-dedicated-docker-linux  |   <AsteroidAmount>0</AsteroidAmount>
space-engineers-dedicated-docker-linux  |   <Administrators>
space-engineers-dedicated-docker-linux  |   </Administrators>
space-engineers-dedicated-docker-linux  |   <Banned />
space-engineers-dedicated-docker-linux  |   <GroupID>0</GroupID>
space-engineers-dedicated-docker-linux  |   <ServerName>Star System</ServerName>
space-engineers-dedicated-docker-linux  |   <WorldName>Star System</WorldName>
space-engineers-dedicated-docker-linux  |   <PauseGameWhenEmpty>false</PauseGameWhenEmpty>
space-engineers-dedicated-docker-linux  |   <MessageOfTheDay />
space-engineers-dedicated-docker-linux  |   <MessageOfTheDayUrl />
space-engineers-dedicated-docker-linux  |   <AutoRestartEnabled>true</AutoRestartEnabled>
space-engineers-dedicated-docker-linux  |   <AutoRestatTimeInMin>720</AutoRestatTimeInMin>
space-engineers-dedicated-docker-linux  |   <AutoRestartSave>true</AutoRestartSave>
space-engineers-dedicated-docker-linux  |   <AutoUpdateEnabled>true</AutoUpdateEnabled>
space-engineers-dedicated-docker-linux  |   <AutoUpdateCheckIntervalInMin>10</AutoUpdateCheckIntervalInMin>
space-engineers-dedicated-docker-linux  |   <AutoUpdateRestartDelayInMin>15</AutoUpdateRestartDelayInMin>
space-engineers-dedicated-docker-linux  |   <AutoUpdateSteamBranch />
space-engineers-dedicated-docker-linux  |   <AutoUpdateBranchPassword />
space-engineers-dedicated-docker-linux  |   <IgnoreLastSession>true</IgnoreLastSession>
space-engineers-dedicated-docker-linux  |   <PremadeCheckpointPath>Z:\appdata\space-engineers\Checkpoint</PremadeCheckpointPath>
space-engineers-dedicated-docker-linux  |   <ServerDescription />
space-engineers-dedicated-docker-linux  |   <ServerPasswordHash />
space-engineers-dedicated-docker-linux  |   <ServerPasswordSalt>technicallythisisbase64</ServerPasswordSalt>
space-engineers-dedicated-docker-linux  |   <Reserved />
space-engineers-dedicated-docker-linux  |   <RemoteApiEnabled>false</RemoteApiEnabled>
space-engineers-dedicated-docker-linux  |   <RemoteSecurityKey>TOppeC56DmRct7rME06hsw==</RemoteSecurityKey>
space-engineers-dedicated-docker-linux  |   <RemoteApiPort>8080</RemoteApiPort>
space-engineers-dedicated-docker-linux  |   <Plugins />
space-engineers-dedicated-docker-linux  |   <WatcherInterval>30</WatcherInterval>
space-engineers-dedicated-docker-linux  |   <WatcherSimulationSpeedMinimum>0.05</WatcherSimulationSpeedMinimum>
space-engineers-dedicated-docker-linux  |   <ManualActionDelay>5</ManualActionDelay>
space-engineers-dedicated-docker-linux  |   <ManualActionChatMessage>Server will be shut down in {0} min(s).</ManualActionChatMessage>
space-engineers-dedicated-docker-linux  |   <AutodetectDependencies>true</AutodetectDependencies>
space-engineers-dedicated-docker-linux  |   <SaveChatToLog>false</SaveChatToLog>
space-engineers-dedicated-docker-linux  | </MyConfigDedicated>/appdata/space-engineers/Plugins
space-engineers-dedicated-docker-linux  |
space-engineers-dedicated-docker-linux  | 0 directories, 0 files
space-engineers-dedicated-docker-linux  | /appdata/space-engineers/World
space-engineers-dedicated-docker-linux  | |-- SpaceEngineers-Dedicated.cfg
space-engineers-dedicated-docker-linux  | `-- World
space-engineers-dedicated-docker-linux  |     |-- Alien-291759539d120000.vx2
space-engineers-dedicated-docker-linux  |     |-- EarthLike-1779144428d120000.vx2
space-engineers-dedicated-docker-linux  |     |-- Europa-595048092d19000.vx2
space-engineers-dedicated-docker-linux  |     |-- Mars-2044023682d120000.vx2
space-engineers-dedicated-docker-linux  |     |-- Moon-1353915701d19000.vx2
space-engineers-dedicated-docker-linux  |     |-- SANDBOX_0_0_0_.sbs
space-engineers-dedicated-docker-linux  |     |-- Sandbox.sbc
space-engineers-dedicated-docker-linux  |     |-- Sandbox_config.sbc
space-engineers-dedicated-docker-linux  |     |-- Titan-2124704365d19000.vx2
space-engineers-dedicated-docker-linux  |     |-- Triton-12345d80253.vx2
space-engineers-dedicated-docker-linux  |     `-- thumb.jpg
space-engineers-dedicated-docker-linux  |
space-engineers-dedicated-docker-linux  | 1 directory, 12 files
space-engineers-dedicated-docker-linux  | ln: failed to create symbolic link '/home/wine/.steam/root': No such file or directory
space-engineers-dedicated-docker-linux  | ln: failed to create symbolic link '/home/wine/.steam/steam': No such file or directory
space-engineers-dedicated-docker-linux  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
space-engineers-dedicated-docker-linux  | Redirecting stderr to '/home/wine/Steam/logs/stderr.txt'
space-engineers-dedicated-docker-linux  | Logging directory: '/home/wine/Steam/logs'
space-engineers-dedicated-docker-linux  | [  0%] Checking for available updates...
space-engineers-dedicated-docker-linux  | [----] Verifying installation...
space-engineers-dedicated-docker-linux  | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1716242337
space-engineers-dedicated-docker-linux  | -- type 'quit' to exit --
space-engineers-dedicated-docker-linux  | Loading Steam API...OK
space-engineers-dedicated-docker-linux  |
space-engineers-dedicated-docker-linux  | Connecting anonymously to Steam Public...OK
space-engineers-dedicated-docker-linux  | Waiting for client config...OK
space-engineers-dedicated-docker-linux  | Waiting for user info...OK
space-engineers-dedicated-docker-linux  | "@sSteamCmdForcePlatformType" = "windows"
space-engineers-dedicated-docker-linux  | Success! App '298740' already up to date.
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.463: App Version: 01_204_018
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.492: Is official: True [NO][NIS][NAMP]
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.496: Client Build Number: 0
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.496: Server Build Number: 0
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.496: Environment.ProcessorCount: 4
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: Environment.OSVersion: Microsoft Windows 7 Professional (Microsoft Windows NT 6.1.7601 Service Pack 1)
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: Environment.CommandLine: "Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64\SpaceEngineersDedicated.exe" -noconsole -path Z:\appdata\space-engineers\SpaceEngineersDedicated -ignorelastsession
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: Environment.Is64BitProcess: True
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: Environment.Is64BitOperatingSystem: True
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: Environment.Version: .NET Framework 4.8.3761.0
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: Environment.CurrentDirectory: Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64
space-engineers-dedicated-docker-linux  | 2024-05-23 17:38:58.509: CPU Info: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
space-engineers-dedicated-docker-linux  | Computer does not meet minimum requirements, forcing Experimental mode
space-engineers-dedicated-docker-linux  | 2024-05-23 17:39:05.020: Bind IP : 0.0.0.0:27016
space-engineers-dedicated-docker-linux  | 2024-05-23 17:39:13.579: Invalid ServerPasswordSalt: technicallythisisbase64 Exception: System.FormatException: Invalid length for a Base-64 char array or string.
space-engineers-dedicated-docker-linux  |    at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
space-engineers-dedicated-docker-linux  |    at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
space-engineers-dedicated-docker-linux  |    at System.Convert.FromBase64String(String s)
space-engineers-dedicated-docker-linux  |    at Sandbox.Engine.Multiplayer.MyDedicatedServerBase.Initialize(IPEndPoint serverEndpoint)
space-engineers-dedicated-docker-linux exited with code 0
server@debian-server:~/space-engineers-dedicated-docker-linux$

what code 0 means? this is only a part of the log. .
Thanks

**Comment by mmmaxwwwell** [comment]
Invalid ServerPasswordSalt: technicallythisisbase64 Exception: System.FormatException: Invalid length for a Base-64 char array

thanks for the report, this is on my todo list

**Comment by mmmaxwwwell** [comment]
you can fix it by making 'technicalythisisbase64' into an actual base64 value in the configs

**Comment by Gragenio** [comment]
done. Thanks

**Comment by mmmaxwwwell** [comment]
I'm going to leave this open until I fix it as a reminder for me

**Comment by Borimino** [comment]
This seems to still be a problem. Thanks to this issue it is easy to fix, though it would be nice to have it either completely fixed or have the fix mentioned in the README.md

**Comment by JaldeaR** [comment]
i tried changing this in the config but the cfg file gets reverted in V2 everytime to plaintext: technicallythisisbase64
```
Invalid ServerPasswordSalt: technicallythisisbase64 Exception: System.FormatException: Invalid length for a Base-64 char array or string.
```
